data_test = [
    ("Como posso incluir grãos integrais no jantar para evitar picos de glicemia pós-prandial?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais são as contraindicações do uso de sitagliptina em pacientes com histórico de pancreatite?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Devo ajustar a dose de insulina glargina em dias de maratona ou treino intensivo?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Posso substituir o arroz branco por couscous integral sem afetar meu controle glicêmico?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais são os sinais de hipoglicemia após tomar glibenclamida antes do café da manhã?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como a ingestão de fibras solúveis influencia a dose de metformina prescrita?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("É seguro usar canela em pó como suplemento diário para ajudar na sensibilidade à insulina?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais efeitos adversos devo monitorar ao combinar liraglutida com estatinas?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Qual o impacto de um café expresso forte nos níveis de glicose em jejum?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como devo dividir a ingestão de carboidratos ao longo do dia para reduzir a necessidade de insulina rápida?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais vegetais fermentados posso incluir para melhorar a saúde intestinal sem alterar muito a glicemia?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("É indicado tomar metformina após a refeição ou posso ingeri-la em jejum?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Como interpretar valores de glicemia capilar acima de 200 mg/dL duas horas após o almoço?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Devo evitar alimentos ricos em FODMAPs quando estiver em tratamento com pioglitazona?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Quais estratégias de refeição posso usar em viagens longas para manter a estabilidade glicêmica?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como escolher um adoçante seguro para receitas de tortas sem interferir na terapia medicamentosa?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais opções de snacks proteicos posso consumir entre o café e o almoço sem prejudicar a glicemia?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quando é recomendado revisar a dosagem de empagliflozina em idosos com função renal reduzida?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como a fibra alimentar presente no feijão impacta o uso de insulina pré-prandial?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("É eficaz praticar jejum intermitente de 16/8 para melhorar HBA1c em diabetes tipo 2?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais cuidados tomar ao usar êmulas de stevia em receitas de pão caseiro?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("Devo ajustar a dose de insulina de ação rápida em refeições com alto teor de gordura?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como posso calcular a carga glicêmica total de um smoothie com frutas e aveia?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais efeitos colaterais gastrointestinais podem ocorrer com metformina de liberação prolongada?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Posso utilizar whey protein após o treino para ajudar na recuperação sem elevação abrupta de glicose?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais parâmetros de CGM devo avaliar em um período de jejum de 12 horas?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como a quantidade de sódio na dieta pode influenciar o uso de inibidores de SGLT2?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("É adequado usar óleo de coco em receitas de bolos para diabéticos sob metformina?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Quando devo medir minha glicemia se consumo bebidas alcoólicas em moderação?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais carboidratos de alto índice glicêmico devo limitar durante o pré-treino?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como posso reduzir a oscilação glicêmica ao misturar frutas com alto teor de açúcar em sucos?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais vitaminas são recomendadas para diabéticos em terapia de insulina?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Devo evitar glúten mesmo sem diagnóstico de doença celíaca para melhor controle glicêmico?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como escolher lanches portáteis que não afetem minha dose diária de insulina?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais nutrientes posso priorizar para reduzir a necessidade de incretinas sintéticas?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("É seguro usar dietas cetogênicas ciclicamente em tratamento de diabetes tipo 2?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como o uso concomitante de estatinas pode influenciar as metas de A1c?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Devo revisar a terapia medicamentosa ao reduzir significativamente a ingestão calórica?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais tipos de exercício reduzem mais rapidamente a glicemia pós-prandial?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como organizar uma dieta low FODMAP sem comprometer o tratamento medicamentoso do diabetes?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("É recomendado ajustar insulina basal em festas comendo sobremesas doces?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais características de refeições pré-treino ajudam a reduzir hipoglicemias tardias?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como a suplementação com magnésio pode afetar a ação da metformina?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Quais ajustes de dieta são necessários ao iniciar inibidores de DPP-4?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Posso usar adoçantes naturais em chás gelados mantendo metas de glicemia?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais recomendações de alimentação pré-cirúrgica impactam a glicemia e uso de insulina?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como escolher entre gliclazida e glimepirida em monoterapia para controle de A1c?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("É benéfico consumir iogurte grego sem lactose para reduzir variações glicêmicas matinais?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quando devo monitorar delta de glicose espontâneo em regime de múltiplas injeções diárias?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
("Como posso ajustar meu plano alimentar em dias de pico de estresse para manter a glicemia estável?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais cuidados devo ter ao iniciar terapia com inibidores de SGLT2 se faço jejum intermitente?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("É seguro consumir suplementos de cromo para melhorar a sensibilidade à insulina?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como interpretar leituras de glicemia contínua que apresentam variações noturnas inesperadas?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Quais são os sinais de interação entre metformina e omeprazol que devo monitorar?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Posso substituir o café normal por chá verde antes das refeições para auxiliar no controle glicêmico?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como calcular a quantidade de insulina necessária para correção de hiperglicemia após um erro na contagem de carboidratos?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Quais vegetais ricos em antioxidantes são recomendados para diabéticos tipo 1?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("É indicado usar fibras solúveis em cápsulas como complemento alimentar para controlar picos de açúcar?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais são as contraindicações do uso de GLP-1 agonistas em pacientes com histórico de pancreatite?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como devo adaptar minha dieta em um cruzeiro onde não conheço a composição nutricional dos pratos?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais métodos de contagem de carboidratos são mais fáceis de usar em viagens longas?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como a suplementação com vitamina D pode afetar a dose de insulina basal?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("É possível prevenir hipoglicemias noturnas apenas ajustando a refeição do jantar?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais indicadores devo usar para avaliar se a dose de sulfonilureia está adequada?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como posso incorporar iogurte probiótico na rotina de quem usa insulina de ação rápida?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Quais abordagens alimentares podem reduzir a resistência à insulina sem uso de medicamentos?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quando é indicado ajustar o esquema de insulina de múltiplas doses ao mudar para uma dieta low-carb?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais chás medicinais podem ajudar no controle glicêmico e são seguros com metformina?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como interpretar valores elevados de glicose em jejum na presença de dieta cetogênica?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("É recomendado ajustar a dose de insulinoterapia ao usar suplementos de ômega-3?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Quais estratégias posso adotar para reduzir o consumo de sódio sem comprometer o controle glicêmico?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como o consumo de frutas tropicais difere na contagem de carboidratos em comparação com frutas de clima temperado?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais cuidados devo ter ao usar insulina de ação prolongada em dias de competição esportiva?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Como montar um prato seguindo a regra do prato médico (½ vegetais, ¼ proteínas, ¼ carboidratos) em jantares fora de casa?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais algoritmos posso usar em um app de telemedicina para detectar padrões de hipoglicemia noturna?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("É eficaz usar pulseiras de monitoramento contínuo de glicose integradas a um chatbot de suporte?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como a variação do horário das refeições impacta a eficácia da dose de insulina pré-prandial?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais fontes de proteína vegetal têm menor impacto no pico glicêmico após o almoço?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Posso usar adoçantes naturais na confecção de pães e bolos para pacientes em terapia combinada?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Como ajustar o nível de insulina basal em dias com maior consumo de saladas e vegetais?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais técnicas de preparo de carnes minimizam o pico glicêmico em refeições ricas em proteína?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("É seguro combinar metformina com suplementos de erva-doce para fins digestivos?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como posso usar análises de séries temporais para prever picos de glicemia em pacientes com T1D?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Quais laticínios fermentados são mais indicados para diabéticos usuários de insulina?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("Devo ajustar a dose de insulina pré-prandial ao consumir alimentos ricos em gorduras saudáveis?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como a personalização de algoritmos de recomendação em telemedicina pode melhorar a adesão ao tratamento?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("É indicado avaliar a variabilidade glicêmica usando métricas de desvio padrão em CGM?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Quais alimentos fermentados podem interferir na absorção de medicamentos antidiabéticos?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":0}}),
    ("Como posso usar prompts de IA para gerar planos alimentares personalizados em um chatbot?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("Posso usar a técnica de contagem de trocas alimentares em conjunto com calculadora de insulina?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Quais são as limitações de modelos de ML em prever eventos de hipoglicemia?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como integrar dados de glucometria e aplicações de nutrição em uma plataforma única?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("É seguro usar aplicativos de telemedicina para ajustar doses de insulina sem consulta médica?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Quais adaptações devo fazer na dieta em um acampamento de alta altitude?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Como a fibra presente em chia impacta a velocidade de absorção de repaglinida?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("É recomendado ajustar doses de medicamentos antidiabéticos em pacientes com disfunção hepática?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como posso usar feedback em tempo real de CGM para modificar escolhas alimentares?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais considerações devo ter ao prescrever insulina em dispositivos de administração em bomba?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Posso usar a técnica de meal prep semanal para garantir melhor controle glicêmico?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais métricas de avaliação devo incluir no dashboard de telemonitoramento glicêmico?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("É seguro ajustar o plano de insulina via chatbot se os sintomas forem leves?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Como garantir a precisão de leitura de glicemia em diferentes marcas de sensores CGM?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Quais recomendações devo seguir ao usar metformina XR versus metformina IR?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como posso usar prompts de NLP para detectar intenções de revisão de dose em mensagens?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("É indicado suplementar cálcio em pacientes em terapia com tiazolidinedionas?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Quais técnicas de mind-mapping ajudam pacientes a planejar refeições balanceadas?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("Como a variação de temperatura corporal pode alterar a eficácia da insulina injetável?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("É seguro usar suplementos proteicos à base de leite em pacientes intolerantes à lactose?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais critérios devo usar para validar um modelo de previsão de glicemia em tempo real?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como ajustar minha rotina alimentar em longas escalas noturnas de trabalho?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Posso usar estratégias de carb cycling para otimizar o controle glicêmico em atletas?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("Quais suplementos de magnésio interagem com medicamentos antidiabéticos?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":0}}),
    ("Como incorporar feedback de dieta em aplicações móveis usando prompts dinâmicos?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":0}}),
    ("É eficaz automatizar a correção de dose de insulina via integração CGM-EHR?",
     {"cats": {"alimentação":0, "medicamento":1, "controle_glicemico":1}}),
    ("Quais práticas de telemonitoramento ajudam a reduzir hospitalizações por hipoglicemia?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
    ("Como posso usar análise de sentimento em mensagens para detectar risco de desmotivação no paciente?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":0}}),  # multilabel none
    ("Quais macronutrientes devo priorizar em recuperação pós-cirúrgica para manter glicemia estável?",
     {"cats": {"alimentação":1, "medicamento":0, "controle_glicemico":1}}),
    ("É indicado tomar insulina ultra-rápida antes de uma refeição rica em gorduras?",
     {"cats": {"alimentação":1, "medicamento":1, "controle_glicemico":1}}),
    ("Como posso gerar alertas automáticos de hiperglicemia em um sistema de telemedicina?",
     {"cats": {"alimentação":0, "medicamento":0, "controle_glicemico":1}}),
]
