ABBREVIATIONS_DICT = {
    # ——— Conversa informal / internet ———
    "vc": "você",
    "cê": "você",
    "ce": "você",
    "vcs": "vocês",
    "pra": "para",
    "tb": "também",
    "tbm": "também",
    "blz": "beleza",
    "pq": "porque",
    "q": "que",
    "qd": "quando",
    "qdo": "quando",
    "qlqr": "qualquer",
    "qt": "quanto",
    "qto": "quanto",
    "dps": "depois",
    "hj": "hoje",
    "fds": "fim de semana",
    "vlw": "valeu",
    "flw": "falou",
    "msg": "mensagem",
    "msm": "mesmo",
    "obg": "obrigado",
    "obgd": "obrigado",
    "td": "tudo",
    "pfv": "por favor",
    "pls": "por favor",
    "pff": "por favor",
    "pf": "por favor",
    "abs": "abraços",
    "nd": "nada",
    "n": "não",
    "ñ": "não",
    "aq": "aqui",
    "cmg": "comigo",
    "glr": "galera",
    "sla": "sei lá",
    "dnv": "de novo",
    "pprt": "papo reto",
    "pft": "perfeito",
    "mt": "muito",
    "mto": "muito",
    "sóh": "só",
    # atalhos com barra
    "c/": "com",
    "s/": "sem",
    "p/": "para",
    # ——— Tratamentos e títulos ———
    "sr.": "senhor",
    "sra.": "senhora",
    "srta.": "senhorita",
    "dr.": "doutor",
    "dra.": "doutora",
    "prof.": "professor",
    "profa.": "professora",
    "ilmo.": "ilustríssimo",
    "v. exa.": "vossa excelência",
    "v. sa.": "vossa senhoria",
    # ——— Editoriais, acadêmicas, gerais ———
    "art.": "artigo",
    "cap.": "capítulo",
    "vol.": "volume",
    "nº": "número",
    "núm.": "número",
    "pág.": "página",
    "pp.": "páginas",
    "aprox.": "aproximadamente",
    "etc.": "et cetera",
    "e.g.": "por exemplo",
    "p. ex.": "por exemplo",
    "vs.": "versus",
    # ——— Unidades & tempo ———
    "kg": "quilograma",
    "g": "grama",
    "km": "quilômetro",
    "m": "metro",
    "cm": "centímetro",
    "mm": "milímetro",
    "h": "hora",
    "hrs": "horas",
    "min": "minuto",
    "seg": "segundo",
    # ——— Negócios & jurídico ———
    "ltda.": "limitada",
    # ——— Diversos ———
    "tel.": "telefone",
    "cel.": "celular",
    "doc.": "documento",
    "ref.": "referência",
}
